name: Auto Add Issues to Project Board

on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project board
        uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/jalez/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
