name: Project Board Automation

on:
  issues:
    types: [opened, labeled, unlabeled]

jobs:
  project_automation:
    runs-on: ubuntu-latest
    steps:
      # Add issues to project when created
      - uses: actions/add-to-project@v0.5.0
        if: github.event.action == 'opened'
        with:
          project-url: https://github.com/users/jalez/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
      
      # Update issue status based on labels
      - name: Get project data
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
          ORGANIZATION: jalez
          PROJECT_NUMBER: 1
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              user(login: $org){
                projectV2(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -f number=$PROJECT_NUMBER > project_data.json

      - uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          github_token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          organization: jalez
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_field: "Status"
          status_value: ${{ 
            contains(github.event.issue.labels.*.name, 'in-progress') && 'In Progress' ||
            contains(github.event.issue.labels.*.name, 'done') && 'Done' ||
            'Todo'
          }}
